# Generated by Django 3.0 on 2020-01-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
