# Generated by Django 3.0.2 on 2020-01-08 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0002_auto_20200108_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='project',
            name='completion_time',
            field=models.DateTimeField(help_text='Project completion time', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Project creation time.'),
            preserve_default=False,
        ),
    ]
